=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "isHomebrew",
        "isSecret",
        "isLocked",
        "skills",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CampingSkill"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "oncePerSession": {
          "type": "boolean"
        },
        "requiredCompanion": {
          "type": "string"
        }
      }
    },
    "CampingSkill": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "dcType",
        "proficiency"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "proficiency": {
          "type": "string",
          "enum": [
            "untrained",
            "trained",
            "expert",
            "master",
            "legendary"
          ]
        },
        "dc": {
          "type": "number"
        },
        "validateOnly": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "dcType": {
          "type": "string",
          "enum": [
            "zone",
            "actorLevel",
            "none",
            "static"
          ]
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Prepare Campsite.json
{
  "id": "prepare-campsite",
  "name": "campingActivities.prepare-campsite.name",
  "isHomebrew": false,
  "skills": [
    {
      "name": "survival",
      "proficiency": "untrained",
      "dcType": "zone"
    }
  ],
  "isSecret": false,
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.Iuen7iSvZAlnAJFB",
  "isLocked": false,
  "criticalSuccess": {
    "message": "campingActivities.prepare-campsite.criticalSuccess.message",
    "modifyRandomEncounterDc": {
      "day": 2,
      "night": 2
    }
  },
  "success": {
    "message": "campingActivities.prepare-campsite.success.message"
  },
  "failure": {
    "message": "campingActivities.prepare-campsite.failure.message",
    "effectUuids": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.X1OvR5j1cAXZ4Lbp"
      }
    ]
  },
  "criticalFailure": {
    "message": "campingActivities.prepare-campsite.criticalFailure.message",
    "checkRandomEncounter": true
  },
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Maintain Armor.json
{
  "id": "maintain-armor",
  "name": "campingActivities.maintain-armor.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.zUaeA8Ud9dv3hhnc",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "requiredCompanion": "Valerie",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Wilderness Survival.json
{
  "id": "wilderness-survival",
  "name": "campingActivities.wilderness-survival.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.8PNH77YHVkw9KoAv",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.v9i9W49PeJ9NkfXX"
    }
  ],
  "requiredCompanion": "Ekundayo",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Set Alarms.json
{
  "id": "set-alarms",
  "name": "campingActivities.set-alarms.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.vWSQmYLKlrk3rLDE",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.ptjs54eoEX8EAQNq"
    }
  ],
  "requiredCompanion": "Octavia",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Camp Management.json
{
  "id": "camp-management",
  "name": "campingActivities.camp-management.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.JRScwsFTXTpTwWYA",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "survival",
      "proficiency": "untrained",
      "dcType": "zone"
    }
  ],
  "criticalSuccess": {
    "message": "campingActivities.camp-management.criticalSuccess.message"
  },
  "success": {
    "message": "campingActivities.camp-management.success.message"
  },
  "criticalFailure": {
    "message": "campingActivities.camp-management.criticalFailure.message",
    "effectUuids": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.vpH13xgAqX4zsU6o"
      }
    ]
  },
  "requiredCompanion": "Jubilost",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Hunt and Gather.json
{
  "id": "hunt-and-gather",
  "name": "campingActivities.hunt-and-gather.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.RujdVNvLpoQBBdVV",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "survival",
      "proficiency": "trained",
      "dcType": "zone",
      "required": true
    },
    {
      "name": "hunting",
      "proficiency": "trained",
      "dcType": "zone"
    }
  ],
  "criticalSuccess": {
    "message": "campingActivities.hunt-and-gather.criticalSuccess.message"
  },
  "success": {
    "message": "campingActivities.hunt-and-gather.success.message"
  },
  "failure": {
    "message": "campingActivities.hunt-and-gather.failure.message"
  },
  "criticalFailure": {
    "message": "campingActivities.hunt-and-gather.criticalFailure.message",
    "checkRandomEncounter": true
  },
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Cook Meal.json
{
  "id": "cook-meal",
  "name": "campingActivities.cook-meal.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.S72BNBTfKfkCjriU",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "criticalSuccess": {
    "message": "campingActivities.cook-meal.criticalSuccess.message"
  },
  "success": {
    "message": "campingActivities.cook-meal.success.message"
  },
  "failure": {
    "message": "campingActivities.cook-meal.failure.message"
  },
  "criticalFailure": {
    "message": "campingActivities.cook-meal.criticalFailure.message"
  },
  "oncePerSession": false
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Bolster Confidence.json
{
  "id": "bolster-confidence",
  "name": "campingActivities.bolster-confidence.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.pxHYFLK7VYGppCzS",
  "isLocked": true,
  "isSecret": false,
  "skills": [],
  "isHomebrew": false,
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.mAEvnTqFuLIASQLB"
    }
  ],
  "requiredCompanion": "Linzi",
  "oncePerSession": true
}
