=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/camping-activity.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/camping-activity.json",
  "title": "Camping Activity",
  "description": "A camping activity",
  "$ref": "#/$defs/CampingActivity",
  "$defs": {
    "CampingActivity": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "isHomebrew",
        "isSecret",
        "isLocked",
        "skills",
        "id"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "journalUuid": {
          "type": "string"
        },
        "skills": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/CampingSkill"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "isSecret": {
          "type": "boolean"
        },
        "isLocked": {
          "type": "boolean"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "success": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "failure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/ActivityOutcome"
        },
        "oncePerSession": {
          "type": "boolean"
        },
        "requiredCompanion": {
          "type": "string"
        }
      }
    },
    "CampingSkill": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "name",
        "dcType",
        "proficiency"
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "proficiency": {
          "type": "string",
          "enum": [
            "untrained",
            "trained",
            "expert",
            "master",
            "legendary"
          ]
        },
        "dc": {
          "type": "number"
        },
        "validateOnly": {
          "type": "boolean"
        },
        "required": {
          "type": "boolean"
        },
        "dcType": {
          "type": "string",
          "enum": [
            "zone",
            "actorLevel",
            "none",
            "static"
          ]
        }
      }
    },
    "ModifyEncounterDc": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "day",
        "night"
      ],
      "properties": {
        "day": {
          "type": "number"
        },
        "night": {
          "type": "number"
        }
      }
    },
    "ActivityEffect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "uuid"
      ],
      "properties": {
        "uuid": {
          "type": "string"
        },
        "target": {
          "type": "string",
          "enum": [
            "all",
            "self",
            "allies"
          ]
        },
        "doublesHealing": {
          "type": "boolean"
        }
      }
    },
    "ActivityOutcome": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "message"
      ],
      "properties": {
        "message": {
          "type": "string"
        },
        "effectUuids": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/ActivityEffect"
          }
        },
        "modifyRandomEncounterDc": {
          "$ref": "#/$defs/ModifyEncounterDc"
        },
        "checkRandomEncounter": {
          "type": "boolean"
        }
      }
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Water Hazards.json
{
  "id": "water-hazards",
  "name": "campingActivities.water-hazards.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.HGcwmsfjVqfLeYhu",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "requiredCompanion": "Kalikke",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Enhance Weapons.json
{
  "id": "enhance-weapons",
  "name": "campingActivities.enhance-weapons.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.2Dn89HrY7gyvQiOH",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "requiredCompanion": "Amiri",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Healer's Blessing.json
{
  "id": "healers-blessing",
  "name": "campingActivities.healers-blessing.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.X4ggcXUe0wPiW4jt",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.eaWmjDOIvUF9aDbq",
      "doublesHealing": true
    }
  ],
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Learn from a Companion.json
{
  "id": "learn-from-a-companion",
  "name": "campingActivities.learn-from-a-companion.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.MyeB2g0yDwEsqfI9",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "perception",
      "dcType": "static",
      "proficiency": "untrained",
      "dc": 20
    }
  ],
  "criticalSuccess": {
    "message": "campingActivities.learn-from-a-companion.criticalSuccess.message"
  },
  "success": {
    "message": "campingActivities.learn-from-a-companion.success.message"
  },
  "failure": {
    "message": "campingActivities.learn-from-a-companion.failure.message"
  },
  "criticalFailure": {
    "message": "campingActivities.learn-from-a-companion.criticalFailure.message"
  },
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Organize Watch.json
{
  "id": "organize-watch",
  "name": "campingActivities.organize-watch.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.wgyPZBRgPjTeK0Ch",
  "isLocked": false,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [
    {
      "name": "perception",
      "proficiency": "expert",
      "dcType": "zone"
    }
  ],
  "criticalSuccess": {
    "message": "campingActivities.organize-watch.criticalSuccess.message",
    "effectUuids": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.010XlkzzjX38BHsO"
      }
    ]
  },
  "success": {
    "message": "campingActivities.organize-watch.success.message",
    "effectUuids": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.MOXWga7l8dsypUPy"
      }
    ]
  },
  "failure": {
    "message": "campingActivities.organize-watch.failure.message"
  },
  "criticalFailure": {
    "message": "campingActivities.organize-watch.criticalFailure.message",
    "checkRandomEncounter": true
  },
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Camouflage Campsite.json
{
  "id": "camouflage-campsite",
  "name": "campingActivities.camouflage-campsite.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.mlLCjokti3RXAlUP",
  "isLocked": false,
  "isSecret": true,
  "isHomebrew": false,
  "skills": [
    {
      "name": "stealth",
      "proficiency": "trained",
      "dcType": "zone"
    }
  ],
  "criticalSuccess": {
    "message": "campingActivities.camouflage-campsite.criticalSuccess.message",
    "modifyRandomEncounterDc": {
      "day": 2,
      "night": 2
    }
  },
  "success": {
    "message": "campingActivities.camouflage-campsite.success.message",
    "modifyRandomEncounterDc": {
      "day": 1,
      "night": 1
    }
  },
  "criticalFailure": {
    "message": "campingActivities.camouflage-campsite.criticalFailure.message",
    "modifyRandomEncounterDc": {
      "day": -2,
      "night": -2
    }
  },
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Enhance Campfire.json
{
  "id": "enhance-campfire",
  "name": "campingActivities.enhance-campfire.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.ytyW9F39m7xf0gx5",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "effectUuids": [
    {
      "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-camping-effects.Item.NFPQHxvpJd2vsKMe"
    }
  ],
  "requiredCompanion": "Kanerah",
  "oncePerSession": true
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/camping-activities/Blend Into The Night.json
{
  "id": "blend-into-the-night",
  "name": "campingActivities.blend-into-the-night.name",
  "journalUuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-journals.JournalEntry.uSTTCqRYCWj7a38F.JournalEntryPage.jz1FI7zSoPLR8iBL",
  "isLocked": true,
  "isSecret": false,
  "isHomebrew": false,
  "skills": [],
  "modifyRandomEncounterDc": {
    "day": 0,
    "night": 2
  },
  "requiredCompanion": "Harrim",
  "oncePerSession": true
}
