=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Currency": {
      "type": "string",
      "enum": [
        "cp",
        "sp",
        "gp",
        "pp"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "id",
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "isSpecialMeal": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "object",
          "required": [
            "value",
            "currency"
          ],
          "properties": {
            "value": {
              "type": "number"
            },
            "currency": {
              "$ref": "#/$defs/Currency"
            }
          }
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "requirements": {
          "type": "string"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Conditions": {
      "type": "object",
      "required": [
        "condition",
        "value"
      ],
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "drained",
            "enfeebled",
            "stupefied",
            "clumsy"
          ]
        },
        "value": {
          "type": "number"
        },
        "afterRest": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "removeWhenPreparingCampsite": {
          "type": "boolean"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "changeFatigueDurationSeconds": {
          "type": "number"
        },
        "reduceConditions": {
          "type": "object",
          "mode": {
            "type": "string",
            "enum": [
              "all",
              "random"
            ]
          },
          "drained": {
            "type": "number"
          },
          "stupefied": {
            "type": "number"
          },
          "clumsy": {
            "type": "number"
          },
          "enfeebled": {
            "type": "number"
          },
          "afterRest": {
            "type": "boolean"
          }
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healMode": {
          "type": "string",
          "enum": [
            "afterConsumption",
            "afterRest",
            "afterConsumptionAndRest"
          ]
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Black Linnorm Stew.json
{
  "id": "black-linnorm-stew",
  "name": "recipes.black-linnorm-stew.name",
  "icon": "icons/tools/cooking/bowl-steaming-brown.webp",
  "basicIngredients": 8,
  "specialIngredients": 3,
  "cookingLoreDC": 43,
  "survivalDC": 45,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.V6uIWe6BVFV9Ewo3",
  "level": 18,
  "cost": {
    "currency": "gp",
    "value": 1200
  },
  "rarity": "rare",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.I2LiwNjrowS5u4UG"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.m3FgRCWbVupkaORL"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.s1DfJpXFkJorHsuu",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.sxr0BsJJGeLyNBgq"
      }
    ]
  },
  "requirements": "master in Arcana or Nature"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Rice-N-Nut Pudding.json
{
  "id": "rice-n-nut-pudding",
  "name": "recipes.rice-n-nut-pudding.name",
  "icon": "icons/consumables/food/pot-soup-white.webp",
  "basicIngredients": 2,
  "specialIngredients": 1,
  "cookingLoreDC": 16,
  "survivalDC": 18,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.IrrRh2yttdTDU1A5",
  "level": 2,
  "cost": {
    "currency": "gp",
    "value": 2
  },
  "rarity": "common",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.3Gj0AaUzqwN0CdTi",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.AI1hYVSAMmKgEO9u",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.GzZYeBB1UGMAykXc",
        "removeAfterRest": true
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.IRTWUl4HjRa82A1B",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "requirements": "trained in Arcana"
}
