=== BernhardPosselt/pf2e-kingmaker-tools/src/commonMain/resources/schemas/recipe.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://posselt.at/pf2e-kingmaker-tools/schemas/recipe.json",
  "title": "Recipe",
  "description": "A recipe",
  "$ref": "#/$defs/Recipe",
  "$defs": {
    "Rarity": {
      "type": "string",
      "enum": [
        "common",
        "uncommon",
        "rare",
        "unique"
      ]
    },
    "Currency": {
      "type": "string",
      "enum": [
        "cp",
        "sp",
        "gp",
        "pp"
      ]
    },
    "Recipe": {
      "type": "object",
      "required": [
        "id",
        "name",
        "basicIngredients",
        "specialIngredients",
        "cookingLoreDC",
        "survivalDC",
        "uuid",
        "level",
        "cost",
        "rarity",
        "criticalSuccess",
        "success",
        "criticalFailure"
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "isSpecialMeal": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "icon": {
          "type": "string"
        },
        "basicIngredients": {
          "type": "number"
        },
        "specialIngredients": {
          "type": "number"
        },
        "cookingLoreDC": {
          "type": "number"
        },
        "survivalDC": {
          "type": "number"
        },
        "uuid": {
          "type": "string"
        },
        "level": {
          "type": "number"
        },
        "cost": {
          "type": "object",
          "required": [
            "value",
            "currency"
          ],
          "properties": {
            "value": {
              "type": "number"
            },
            "currency": {
              "$ref": "#/$defs/Currency"
            }
          }
        },
        "rarity": {
          "$ref": "#/$defs/Rarity"
        },
        "isHomebrew": {
          "type": "boolean"
        },
        "requirements": {
          "type": "string"
        },
        "criticalSuccess": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "success": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "criticalFailure": {
          "$ref": "#/$defs/CookingOutcome"
        },
        "favoriteMeal": {
          "$ref": "#/$defs/CookingOutcome"
        }
      }
    },
    "CookingOutcome": {
      "type": "object",
      "properties": {
        "effects": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/MealEffect"
          }
        },
        "chooseRandomly": {
          "type": "boolean"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Conditions": {
      "type": "object",
      "required": [
        "condition",
        "value"
      ],
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "drained",
            "enfeebled",
            "stupefied",
            "clumsy"
          ]
        },
        "value": {
          "type": "number"
        },
        "afterRest": {
          "type": "boolean"
        }
      }
    },
    "MealEffect": {
      "type": "object",
      "properties": {
        "uuid": {
          "type": "string"
        },
        "removeWhenPreparingCampsite": {
          "type": "boolean"
        },
        "changeRestDurationSeconds": {
          "type": "number"
        },
        "changeFatigueDurationSeconds": {
          "type": "number"
        },
        "reduceConditions": {
          "type": "object",
          "mode": {
            "type": "string",
            "enum": [
              "all",
              "random"
            ]
          },
          "drained": {
            "type": "number"
          },
          "stupefied": {
            "type": "number"
          },
          "clumsy": {
            "type": "number"
          },
          "enfeebled": {
            "type": "number"
          },
          "afterRest": {
            "type": "boolean"
          }
        },
        "doublesHealing": {
          "type": "boolean"
        },
        "halvesHealing": {
          "type": "boolean"
        },
        "healMode": {
          "type": "string",
          "enum": [
            "afterConsumption",
            "afterRest",
            "afterConsumptionAndRest"
          ]
        },
        "healFormula": {
          "type": "string"
        },
        "damageFormula": {
          "type": "string"
        }
      },
      "required": [
        "uuid"
      ]
    }
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Chocolate Ice Cream.json
{
  "id": "chocolate-ice-cream",
  "name": "recipes.chocolate-ice-cream.name",
  "icon": "icons/tools/laboratory/powder-red.webp",
  "basicIngredients": 2,
  "specialIngredients": 1,
  "cookingLoreDC": 19,
  "survivalDC": 21,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.xfIwKyG1pNFp8JbN",
  "level": 4,
  "cost": {
    "currency": "sp",
    "value": 5
  },
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.0QmbpFYAoyzUu1gi"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.9brr5UKBsZcboAOx",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.KqktmooFbYLQQ2S1",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.L85BNpJEFAozA9kW",
        "removeAfterRest": true
      }
    ]
  },
  "requirements": "ability to cast cold spell"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Grilled Silver Eel.json
{
  "id": "grilled-silver-eel",
  "name": "recipes.grilled-silver-eel.name",
  "icon": "icons/commodities/biological/tail-rodent-orange.webp",
  "basicIngredients": 4,
  "specialIngredients": 1,
  "cookingLoreDC": 24,
  "survivalDC": 26,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.UMgvKT6nNTPvp28R",
  "level": 6,
  "cost": {
    "currency": "gp",
    "value": 13
  },
  "rarity": "common",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Dj9026jn8dI7oP0j",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Vb39DIJ5OfWpN2ig",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Zw8I0G3RqDfNHuCl",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.ta81jwzhkNsN88EZ",
        "removeWhenPreparingCampsite": false
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Supernatural Mince Pie.json
{
  "id": "first-world-mince-pie",
  "name": "recipes.first-world-mince-pie.name",
  "icon": "icons/consumables/food/cheese-round-glowing-yellow.webp",
  "basicIngredients": 8,
  "specialIngredients": 4,
  "cookingLoreDC": 45,
  "survivalDC": 47,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.RmMZWrzgd8Wh8z5H",
  "level": 20,
  "cost": {
    "currency": "gp",
    "value": 3500
  },
  "rarity": "rare",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.69VWFB5UNLau1Rzt",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.OAxcELiLh04BLVvP",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.WVRQf9SLX0iRh3Ur",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.69MQw1WMMlN4hEzb",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.yLf2n65zVocqsl6r",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.sd45BQ4P7BtsYEuP",
        "removeWhenPreparingCampsite": false
      }
    ],
    "chooseRandomly": true
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.72N0nZAAo2iuCGBd",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.iV22sORhjIhWZMKw",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.CQGJi8WiBq0T8Kc6",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.L8HdDXKrfa3gDakt",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.6CjFExnLSe9qij9z",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Af25wacbdYDnFKwM",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.VhzUKWFVrZ7tgcEQ",
        "removeWhenPreparingCampsite": false
      }
    ],
    "chooseRandomly": true
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Wfmt1NvfIqF3gFav"
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Kameberry Pie.json
{
  "id": "kameberry-pie",
  "name": "recipes.kameberry-pie.name",
  "icon": "icons/consumables/grains/pastry-bread-brown.webp",
  "basicIngredients": 3,
  "specialIngredients": 2,
  "cookingLoreDC": 27,
  "survivalDC": 29,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.zX4S7wsOxB8CcVWw",
  "level": 10,
  "cost": {
    "currency": "gp",
    "value": 50
  },
  "rarity": "uncommon",
  "requirements": "master in Religion",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.fd6987d921e942728f8bb1a6",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.3dbaaa54cd5a4c3486505ce5",
        "removeAfterRest": true
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.0f332e8028c045b187bfe50f",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.52fa04d46b2241bdb43657f2",
        "removeWhenPreparingCampsite": false
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Seasoned Wings And Thighs.json
{
  "id": "seasoned-wings-and-thighs",
  "name": "recipes.seasoned-wings-and-thighs.name",
  "icon": "icons/consumables/food/chicken-bird-cooked.webp",
  "basicIngredients": 4,
  "specialIngredients": 2,
  "cookingLoreDC": 30,
  "survivalDC": 32,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.BTKN1IgANoof0tfB",
  "level": 12,
  "cost": {
    "currency": "gp",
    "value": 100
  },
  "rarity": "uncommon",
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.uchgkN3hm1T51zfM",
        "removeAfterRest": true
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.JqKhpMXiQCEsDSCw"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.q3vnRHRBn3HmRhkV",
        "removeAfterRest": true
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.xF0K40VzyjIbbRMA",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "requirements": "ability to cast fire spell"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Monster Casserole.json
{
  "id": "monster-casserole",
  "name": "recipes.monster-casserole.name",
  "icon": "icons/consumables/food/soup-broth-bowl-tentacle.webp",
  "basicIngredients": 7,
  "specialIngredients": 2,
  "cookingLoreDC": 28,
  "survivalDC": 30,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.gqT2VQGYgDQIMYsW",
  "level": 11,
  "cost": {
    "currency": "gp",
    "value": 70
  },
  "rarity": "uncommon",
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.5GT0JeRjYJc8e5ZA",
        "removeAfterRest": true
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.af6hFeUUfsF1GiX8",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.gNGXKMmJdNQJZode",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.qad6gIwEpQQIkZwQ",
        "removeWhenPreparingCampsite": false
      }
    ]
  }
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Hearty Purple Soup.json
{
  "id": "hearty-purple-soup",
  "name": "recipes.hearty-purple-soup.name",
  "icon": "icons/tools/laboratory/mortar-liquid-pink.webp",
  "basicIngredients": 6,
  "specialIngredients": 3,
  "cookingLoreDC": 40,
  "survivalDC": 42,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.yAB0s5JgzCZpf0dT",
  "level": 16,
  "cost": {
    "currency": "gp",
    "value": 500
  },
  "rarity": "rare",
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.6RjaP1s58ITIVn6u"
      }
    ]
  },
  "success": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.Zn0CB7bL7vHrMNTU"
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.hLGCjXajAYEcII9J"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.o6F8QZbTvt9os8Ni",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.TQXXVzD1ZZHnouTI",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.SJvEGeMryIekwIKk",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "requirements": "master in Nature"
}

=== BernhardPosselt/pf2e-kingmaker-tools/data/recipes/Cheese Crostata.json
{
  "id": "cheese-crostata",
  "name": "recipes.cheese-crostata.name",
  "icon": "icons/consumables/food/cheese-wheel-round-yellow.webp",
  "basicIngredients": 4,
  "specialIngredients": 0,
  "cookingLoreDC": 22,
  "survivalDC": 24,
  "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.GAf8W01ppdseIGbq",
  "level": 5,
  "cost": {
    "currency": "gp",
    "value": 8
  },
  "rarity": "common",
  "success": {
    "effects": [
      {
        "changeFatigueDurationSeconds": 7200,
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.1VchCdA1LMBhYENe",
        "removeWhenPreparingCampsite": false
      }
    ]
  },
  "favoriteMeal": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.2c2nrlkL2XJXXQIA"
      }
    ]
  },
  "criticalFailure": {
    "effects": [
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.EBa9BjdANCMLKMEy",
        "removeAfterRest": true
      }
    ]
  },
  "criticalSuccess": {
    "effects": [
      {
        "changeFatigueDurationSeconds": 14400,
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.MI6MF3R5OswdGBUd",
        "removeWhenPreparingCampsite": false
      },
      {
        "uuid": "Compendium.pf2e-kingmaker-tools.kingmaker-tools-meal-effects.Item.X7fTfenq4TukJJM4"
      }
    ]
  }
}
